import type { JobData } from '@/components/JobCard'

export const MOCK_JOBS: JobData[] = [
  {
    id: '1',
    companyName: '株式会社テックイノベーション',
    title: 'シニアフロントエンドエンジニア',
    location: '東京都渋谷区',
    remoteOk: true,
    description:
      'React/Next.jsを用いた大規模Webアプリケーションの開発をリードしていただきます。チーム5名のテックリードとして、設計・実装・コードレビューを担当。',
    salaryMin: 700,
    salaryMax: 1000,
    employmentType: 'full_time',
    sourceType: 'direct',
    agentName: null,
    sourceUrl: 'https://example.com/jobs/1',
    matchScore: 92,
  },
  {
    id: '2',
    companyName: '株式会社グローバルソリューションズ',
    title: 'バックエンドエンジニア（Go/Python）',
    location: '東京都港区',
    remoteOk: true,
    description:
      'マイクロサービスアーキテクチャを採用したSaaSプラットフォームの開発。Go言語でのAPI開発、Pythonでのデータパイプライン構築を担当。',
    salaryMin: 600,
    salaryMax: 900,
    employmentType: 'full_time',
    sourceType: 'agent',
    agentName: 'リクルートエージェント',
    sourceUrl: 'https://example.com/jobs/2',
    matchScore: 85,
  },
  {
    id: '3',
    companyName: '合同会社デジタルクラフト',
    title: 'UIデザイナー',
    location: '大阪府大阪市',
    remoteOk: false,
    description:
      '自社プロダクトのUI/UXデザインを担当。Figmaを使用したデザインシステムの構築・運用、ユーザーリサーチに基づくデザイン改善。',
    salaryMin: 450,
    salaryMax: 650,
    employmentType: 'full_time',
    sourceType: 'direct',
    agentName: null,
    sourceUrl: 'https://example.com/jobs/3',
    matchScore: 78,
  },
  {
    id: '4',
    companyName: '株式会社クラウドベース',
    title: 'インフラエンジニア（AWS）',
    location: '東京都千代田区',
    remoteOk: true,
    description:
      'AWSを中心としたクラウドインフラの設計・構築・運用。Terraform/CDKによるIaC、CI/CDパイプラインの整備、監視体制の構築。',
    salaryMin: 550,
    salaryMax: 850,
    employmentType: 'full_time',
    sourceType: 'agent',
    agentName: 'doda',
    sourceUrl: 'https://example.com/jobs/4',
    matchScore: 73,
  },
  {
    id: '5',
    companyName: '株式会社ヘルステック',
    title: 'プロダクトマネージャー',
    location: '東京都新宿区',
    remoteOk: false,
    description:
      'ヘルスケア領域のBtoB SaaSプロダクトのPM。事業戦略に基づくロードマップ策定、開発チームとの連携、KPI設計・分析。',
    salaryMin: 650,
    salaryMax: 950,
    employmentType: 'full_time',
    sourceType: 'direct',
    agentName: null,
    sourceUrl: 'https://example.com/jobs/5',
    matchScore: 68,
  },
  {
    id: '6',
    companyName: '株式会社フィンテックラボ',
    title: 'データサイエンティスト',
    location: '福岡県福岡市',
    remoteOk: true,
    description:
      '金融データを活用した与信モデルの開発・改善。Python/SQLでの分析基盤構築、機械学習モデルの本番適用、A/Bテスト設計。',
    salaryMin: 500,
    salaryMax: 800,
    employmentType: 'contract',
    sourceType: 'agent',
    agentName: 'JACリクルートメント',
    sourceUrl: 'https://example.com/jobs/6',
    matchScore: 61,
  },
]
